apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    name: cartservice
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0
      value:
        name: DB_HOST
        value: localhost
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: DB_PORT
        value: "5432"
    - op: replace
      path: /spec/template/spec/containers/0/env/2
      value:
        name: DB_USER
        value: postgres
    - op: replace
      path: /spec/template/spec/containers/0/env/3
      value:
        name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: alloydb-secret
            key: postgresql-password
    - op: replace
      path: /spec/template/spec/containers/0/env/4
      value:
        name: DB_NAME
        value: carts
