apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-sidecar-monitor
  namespace: default
  labels:
    app: istio
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchExpressions:
    - key: security.istio.io/tlsMode
      operator: Exists
  endpoints:
  - port: http-envoy-prom
    path: /stats/prometheus
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      targetLabel: service
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      targetLabel: version
      action: replace
