# components/observability/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - prometheus/service-monitors/istio-monitors.yaml
  - jaeger/telemetry.yaml
  - jaeger/provider.yaml

configMapGenerator:
# Grafana dashboards
- name: grafana-dashboards
  namespace: monitoring
  files:
  - dashboards/cluster.json
  - dashboards/services.json
  - dashboards/business.json
  # - dashboards/istio-mesh.json
  # - dashboards/istio-workload.json
  # - dashboards/istio-service.json
  options:
    labels:
      grafana_dashboard: "1"

# ✅ Add Jaeger datasource for Grafana
- name: grafana-datasources
  namespace: monitoring
  files:
  - grafana/datasources.yaml
  options:
    labels:
      grafana_datasource: "1"

# Prometheus rules
- name: prometheus-rules
  namespace: monitoring
  files:
  - prometheus/rules/recording-rules.yaml
  - prometheus/rules/alerting-rules.yaml
  options:
    labels:
      prometheus_rule: "1"

