patches:
- path: ../../components/spot-patch/spot-patch.yaml
  target:
    kind: Deployment
    labelSelector: "app in (adservice,cartservice,checkoutservice,currencyservice,emailservice,frontend,paymentservice,productcatalogservice,recommendationservice,redis-cart)"
