apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-configuration
  namespace: istio-system
spec:
  values:
    global:
      meshConfig:
        defaultConfig:
          tracing:
            zipkin:
              address: jaeger.istio-system:9411
