# components/observability/helm-values/jaeger-values.yaml
provisionDataStore:
  cassandra: false

storage:
  type: memory
  options:
    memory:
      max-traces: 10000

agent:
  enabled: true

collector:
  enabled: true
  otlp:
    enabled: true

query:
  enabled: true
  service:
    type: ClusterIP
    port: 16686