# components/observability/helm-values/kiali-values.yaml
auth:
  strategy: anonymous

deployment:
  accessible_namespaces: ['**']

external_services:
  prometheus:
    url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
  grafana:
    url: http://prometheus-grafana.monitoring.svc.cluster.local:80
  tracing:
    enabled: true
    use_grpc: true
    internal_url: http://jaeger.istio-system.svc.cluster.local:16685
    url: http://jaeger.istio-system.svc.cluster.local:16686

kiali_feature_flags:
  clustering:
    autodetect: true
  certificates_information_indicator: true
  istio_upgrade_indicator: true
  istio_environment_info: true

server:
  port: 20001
  web_root: /kiali