apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    name: cartservice
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env
      value:
      - name: DB_HOST
        value: host.docker.internal
      - name: DB_PORT
        value: "5432"
      - name: DB_USER
        value: postgres
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: alloydb-secret
            key: postgresql-password
      - name: DB_NAME
        value: carts
      - name: DB_TABLE
        value: cart_items
